services:
  web:
    build: .
    container_name: flask-smorest-api
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    working_dir: /app
    command: flask run --host=0.0.0.0 --port=5000
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD = password
      - POSTGRES_DB = myapp 
    volumes:
      -postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

